
import javax.swing.*;
import java.awt.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pakis
 */
public class DeveloperUI extends javax.swing.JFrame {
    Task task;

    /**
     * Creates new form DeveloperUI
     */
    public DeveloperUI() {
        initComponents();
        Image icon = new ImageIcon(this.getClass().getResource("/img/w.png")).getImage();
        this.setIconImage(icon);
    }

    public DeveloperUI(Task task) {
        initComponents();
        Image icon = new ImageIcon(this.getClass().getResource("/img/w.png")).getImage();
        this.setIconImage(icon);
        this.task = task;
        this.setTextArea(task);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_InProgress = new javax.swing.JButton();
        btn_Done = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kanban driven(WPMS)");
        setMaximumSize(new java.awt.Dimension(391, 515));
        setMinimumSize(new java.awt.Dimension(391, 515));
        setResizable(false);
        getContentPane().setLayout(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(25, 25, 25));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 90, 200, 250);

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Update your status!!!");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(130, 360, 140, 20);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TASK");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 50, 60, 32);

        btn_InProgress.setBackground(new java.awt.Color(255, 153, 0));
        btn_InProgress.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        btn_InProgress.setForeground(new java.awt.Color(255, 255, 255));
        btn_InProgress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/INPROGRESS_2.png"))); // NOI18N
        btn_InProgress.setBorder(null);
        btn_InProgress.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_InProgress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InProgressActionPerformed(evt);
            }
        });
        getContentPane().add(btn_InProgress);
        btn_InProgress.setBounds(60, 400, 120, 40);

        btn_Done.setBackground(new java.awt.Color(51, 204, 0));
        btn_Done.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        btn_Done.setForeground(new java.awt.Color(255, 255, 255));
        btn_Done.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Done_1.png"))); // NOI18N
        btn_Done.setBorder(null);
        btn_Done.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DoneActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Done);
        btn_Done.setBounds(210, 400, 120, 40);

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Frame 34 (3).png"))); // NOI18N
        BackButton.setAlignmentX(50.0F);
        BackButton.setAlignmentY(50.0F);
        BackButton.setBorder(null);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(10, 10, 50, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rectangle 66 (2).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 391, 515);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InProgressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InProgressActionPerformed
        // TODO add your handling code here:
        this.task.setColumn_e("InProgress");
        setTextArea(task);
        JOptionPane.showMessageDialog(null, "Updated!");
        LoginRegistration2 LR2 = new LoginRegistration2(task);
        this.dispose();
        LR2.setVisible(true);
    }//GEN-LAST:event_btn_InProgressActionPerformed

    private void btn_DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DoneActionPerformed
        // TODO add your handling code here:
        this.task.setColumn_e("Done");
        setTextArea(task);
        JOptionPane.showMessageDialog(null, "Updated!");
        LoginRegistration2 LR2 = new LoginRegistration2(task);
        this.dispose();
        LR2.setVisible(true);
    }//GEN-LAST:event_btn_DoneActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed

        LoginRegistration2 devscreen = new LoginRegistration2();
        this.dispose();
        devscreen.setVisible(true);

    }//GEN-LAST:event_BackButtonActionPerformed

    private void setTextArea(Task tasks){
        //removing previous data
        jTextArea1.setText("");

        jTextArea1.append("------------------------------------------\n");
        jTextArea1.append(" Project Name     : " + task.getProjectName() + "\n");
        jTextArea1.append(" Task Name        : " +task.getTask_name() + "\n");
        jTextArea1.append(" Task Description : " + task.getTask_description() + "\n");
        jTextArea1.append(" Priority         : " + task.getPriority() + "\n");
        jTextArea1.append(" Deadline         : " + task.getDateInString() + "\n\n");
        jTextArea1.append(" Status           : " + task.getColumn_name() + "\n");


    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeveloperUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeveloperUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeveloperUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeveloperUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//            }

//        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton btn_Done;
    private javax.swing.JButton btn_InProgress;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
